// @generated by protobuf-ts 2.8.3
// @generated from protobuf file "mail.proto" (package "sheets", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EmailService } from "./mail";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Result } from "./mail";
import type { EmailMessage } from "./mail";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service sheets.EmailService
 */
export interface IEmailServiceClient {
    /**
     * @generated from protobuf rpc: SendEmail(sheets.EmailMessage) returns (sheets.Result);
     */
    sendEmail(input: EmailMessage, options?: RpcOptions): UnaryCall<EmailMessage, Result>;
}
/**
 * @generated from protobuf service sheets.EmailService
 */
export class EmailServiceClient implements IEmailServiceClient, ServiceInfo {
    typeName = EmailService.typeName;
    methods = EmailService.methods;
    options = EmailService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SendEmail(sheets.EmailMessage) returns (sheets.Result);
     */
    sendEmail(input: EmailMessage, options?: RpcOptions): UnaryCall<EmailMessage, Result> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmailMessage, Result>("unary", this._transport, method, opt, input);
    }
}
