// @generated by protobuf-ts 2.8.3
// @generated from protobuf file "sheets.proto" (package "sheets", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SheetsService } from "./sheets";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PitAsPDF } from "./sheets";
import type { GetPitPDFRequest } from "./sheets";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service sheets.SheetsService
 */
export interface ISheetsServiceClient {
    /**
     * @generated from protobuf rpc: GetPitPDF(sheets.GetPitPDFRequest) returns (sheets.PitAsPDF);
     */
    getPitPDF(input: GetPitPDFRequest, options?: RpcOptions): UnaryCall<GetPitPDFRequest, PitAsPDF>;
}
/**
 * @generated from protobuf service sheets.SheetsService
 */
export class SheetsServiceClient implements ISheetsServiceClient, ServiceInfo {
    typeName = SheetsService.typeName;
    methods = SheetsService.methods;
    options = SheetsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetPitPDF(sheets.GetPitPDFRequest) returns (sheets.PitAsPDF);
     */
    getPitPDF(input: GetPitPDFRequest, options?: RpcOptions): UnaryCall<GetPitPDFRequest, PitAsPDF> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPitPDFRequest, PitAsPDF>("unary", this._transport, method, opt, input);
    }
}
