# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from database import sheets_pb2 as database_dot_sheets__pb2


class SpreadsheetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/database.sheets.SpreadsheetService/GetUser',
                request_serializer=database_dot_sheets__pb2.GetUserRequest.SerializeToString,
                response_deserializer=database_dot_sheets__pb2.UserResponse.FromString,
                )
        self.GetSheet = channel.unary_unary(
                '/database.sheets.SpreadsheetService/GetSheet',
                request_serializer=database_dot_sheets__pb2.GetSheetRequest.SerializeToString,
                response_deserializer=database_dot_sheets__pb2.SheetResponse.FromString,
                )


class SpreadsheetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSheet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpreadsheetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=database_dot_sheets__pb2.GetUserRequest.FromString,
                    response_serializer=database_dot_sheets__pb2.UserResponse.SerializeToString,
            ),
            'GetSheet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSheet,
                    request_deserializer=database_dot_sheets__pb2.GetSheetRequest.FromString,
                    response_serializer=database_dot_sheets__pb2.SheetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'database.sheets.SpreadsheetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpreadsheetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.sheets.SpreadsheetService/GetUser',
            database_dot_sheets__pb2.GetUserRequest.SerializeToString,
            database_dot_sheets__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSheet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.sheets.SpreadsheetService/GetSheet',
            database_dot_sheets__pb2.GetSheetRequest.SerializeToString,
            database_dot_sheets__pb2.SheetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
