# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sheetsEditor_pb2 as sheetsEditor__pb2


class SheetsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPitPDF = channel.unary_unary(
                '/sheets.SheetsService/GetPitPDF',
                request_serializer=sheetsEditor__pb2.GetPitPDFRequest.SerializeToString,
                response_deserializer=sheetsEditor__pb2.PitAsPDF.FromString,
                )


class SheetsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPitPDF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SheetsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPitPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPitPDF,
                    request_deserializer=sheetsEditor__pb2.GetPitPDFRequest.FromString,
                    response_serializer=sheetsEditor__pb2.PitAsPDF.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sheets.SheetsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SheetsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPitPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sheets.SheetsService/GetPitPDF',
            sheetsEditor__pb2.GetPitPDFRequest.SerializeToString,
            sheetsEditor__pb2.PitAsPDF.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
